version: '3.2' 
services:   

  cassandra-1:
    image: cassandra:latest
    container_name: cassandra-1
    ports:
      - "9042:9042"
    #volumes:
    #  - C:\Users\jasle.carrasco\Desktop\TFG\docker\cassandra-1:/var/lib/cassandra       
    environment:
      - CASSANDRA_RPC_ADDRESS=cassandra-1 
    #  - CASSANDRA_LISTEN_ADDRESS=cassandra  
      - CASSANDRA_SEEDS=cassandra-1,cassandra-2,cassandra-3   
    networks:
    - cassandra
      
  cassandra-2:
    image: cassandra:latest
    container_name: cassandra-2
    ports:
      - "9043:9042"
    depends_on:
      - cassandra-1      
    environment:
      - CASSANDRA_RPC_ADDRESS=cassandra-2    
      - CASSANDRA_SEEDS=cassandra-1,cassandra-2,cassandra-3           
    networks:
    - cassandra       
     
      
  cassandra-3:
    image: cassandra:latest
    container_name: cassandra-3  
    ports:
      - "9044:9042"
    depends_on:
      - cassandra-2     
    environment:
      - CASSANDRA_RPC_ADDRESS=cassandra-3  
      - CASSANDRA_SEEDS=cassandra-1,cassandra-2,cassandra-3       
    networks:
    - cassandra
    
       
networks:
  cassandra:    
    name: cassandra  
  
     
     